#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyside2-setup
Version  : 5.11.2
Release  : 1
URL      : http://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.11.2-src/pyside-setup-everywhere-src-5.11.2.tar.xz
Source0  : http://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.11.2-src/pyside-setup-everywhere-src-5.11.2.tar.xz
Summary  : Support library for Python bindings of Qt5-based libraries.
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0
BuildRequires : Sphinx
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-kde
BuildRequires : buildreq-qmake
BuildRequires : libxml2
BuildRequires : libxml2-dev
BuildRequires : libxslt
BuildRequires : libxslt-dev
BuildRequires : llvm
BuildRequires : llvm-dev
BuildRequires : numpy
BuildRequires : python3-dev
BuildRequires : qtbase-dev
BuildRequires : qtwebengine-dev
Patch1: build.patch

%description
The SameGame example can interface with a simple PHP script to store XML high score data on a remote server. We do not have a publically accessible server available for this use, but if you have access to a PHP capable webserver you can copy the files (score_data.xml, score.php, score_style.xsl) to it and alter the highscore_server variable at the top of the samegame.js file to point to it.

%prep
%setup -q -n pyside-setup-everywhere-src-5.11.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543940483
export CC=clang
export CXX=clang++
export LD=ld.gold
unset LDFLAGS
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyside2-setup
cp LICENSE.FDL %{buildroot}/usr/share/package-licenses/pyside2-setup/LICENSE.FDL
cp LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/pyside2-setup/LICENSE.GPL2
cp LICENSE.GPLv3 %{buildroot}/usr/share/package-licenses/pyside2-setup/LICENSE.GPLv3
cp LICENSE.GPLv3-EXCEPT %{buildroot}/usr/share/package-licenses/pyside2-setup/LICENSE.GPLv3-EXCEPT
cp LICENSE.LGPLv3 %{buildroot}/usr/share/package-licenses/pyside2-setup/LICENSE.LGPLv3
cp sources/patchelf/COPYING %{buildroot}/usr/share/package-licenses/pyside2-setup/sources_patchelf_COPYING
cp sources/pyside2-tools/LICENSE-lupdate %{buildroot}/usr/share/package-licenses/pyside2-setup/sources_pyside2-tools_LICENSE-lupdate
cp sources/pyside2-tools/LICENSE-rcc %{buildroot}/usr/share/package-licenses/pyside2-setup/sources_pyside2-tools_LICENSE-rcc
cp sources/pyside2/COPYING %{buildroot}/usr/share/package-licenses/pyside2-setup/sources_pyside2_COPYING
cp sources/pyside2/PySide2/licensecomment.txt %{buildroot}/usr/share/package-licenses/pyside2-setup/sources_pyside2_PySide2_licensecomment.txt
cp sources/pyside2/doc/codesnippets/examples/dialogs/licensewizard/licensewizard.cpp %{buildroot}/usr/share/package-licenses/pyside2-setup/sources_pyside2_doc_codesnippets_examples_dialogs_licensewizard_licensewizard.cpp
cp sources/pyside2/doc/codesnippets/examples/dialogs/licensewizard/licensewizard.h %{buildroot}/usr/share/package-licenses/pyside2-setup/sources_pyside2_doc_codesnippets_examples_dialogs_licensewizard_licensewizard.h
cp sources/shiboken2/ApiExtractor/COPYING %{buildroot}/usr/share/package-licenses/pyside2-setup/sources_shiboken2_ApiExtractor_COPYING
cp sources/shiboken2/COPYING %{buildroot}/usr/share/package-licenses/pyside2-setup/sources_shiboken2_COPYING
cp sources/shiboken2/COPYING.libsample %{buildroot}/usr/share/package-licenses/pyside2-setup/sources_shiboken2_COPYING.libsample
cp sources/shiboken2/COPYING.libshiboken %{buildroot}/usr/share/package-licenses/pyside2-setup/sources_shiboken2_COPYING.libshiboken
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)
